#! /bin/sh
bspc rule -r "*"
#pkill -USR1 -x sxhkd &
sxhkd &
picom --experimental-backends &

bspc monitor -d 1 2 3 4 5

bspc config border_width         5
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config border_radius 5
#bspc config bottom_padding 0
bspc config top_padding 40

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# exec alacritty &/??????
exec ~/bin/eww daemon &
feh --bg-fill $HOME/Pictures/Wallpapers/sunset4k.jpg &
bspc config normal_border_color "#414458"
bspc config active_border_color "#42a7d6"
bspc config focused_border_color "#42a7d6"
bspc config presel_feedback_color "#B043D1"
bspc config focus_follows_pointer true

# Window Rules
#sleep 1
#wmctrl -r Spotify -t 9 
#exit
#bspc rule -a Spotify state=floating rectangle=500x500+500+500 sticky=off
#bspc rule -a Alacritty state=floating rectangle 600x900+200+50 sticky=off
bspc rule -a Pavucontrol state=floating rectangle 200x200+50+50 sticky=off 

# Remove x cursor
xsetroot -cursor_name left_ptr & 

dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nm-applet & 
blueman &
exec ~/.config/polybar/launch.sh --blocks
xinput set-prop "AlpsPS/2 ALPS GlidePoint" "libinput Tapping Enabled" 1
xinput set-prop "AlpsPS/2 ALPS GlidePoint" "libinput Natural Scrolling Enabled" 1
notify-send "Logined As Uday"
